name: Build source code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04  # Используем конкретную версию runner-образа для стабильности

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.ref != 'refs/heads/master')
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, xml, curl, zip, pdo, pdo_mysql, gd, json
          coverage: none

      - name: Install dependencies
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.ref != 'refs/heads/master')
        run: |
          sudo apt-get update && sudo apt-get install -y git
          composer install --no-dev --prefer-dist

      - name: Download source code
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.ref != 'refs/heads/master')
        run: |
          mkdir -p ~/build
          git clone --depth=1 https://github.com/irbees2008/ngcms-core ~/build/
          git clone --depth=1 https://github.com/irbees2008/ngcms-plugins ~/build/engine/plugins/

      - name: Install libraries via composer
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.ref != 'refs/heads/master')
        run: |
          cd ~/build
          composer install --no-dev --prefer-dist
          echo ${{ github.sha }} > engine/cache/build

      - name: Cleanup
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.ref != 'refs/heads/master')
        run: |
          cd ~/build
          rm -rf .git
          rm -rf .github
          rm -rf engine/plugins/.git
          mkdir -p ~/package
          tar -czf ~/package/ngcms-current-build.tgz .

      - name: Upload artifact
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.ref != 'refs/heads/master')
        uses: actions/upload-artifact@v4
        with:
          name: ngcms-current-build
          path: ~/package
